# [Zaib's AI Notebook](https://github.com/zaibgray/pandas) | Pandas

What is Pandas
Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

[About Pandas](https://pandas.pydata.org/about/index.html)

## The Big Picture
Think of Pandas like Microsoft Excel inside Python:
- DataFrame = The entire Excel Sheet.
- Series = A single column in that sheet.
- Index = The row numbers on the far left.

### 1. Series (1D Column)
A Series is just a single column of data.
- It can hold any data type (numbers, strings, booleans).
- Every item in a Series must be the same type.

### 2. DataFrame (2D Table)
A DataFrame is the main table structure.
- It is made by gluing multiple Series together side-by-side.
- Different columns can have different data types (e.g., text in one column, numbers in another).

### 3. Index (The Labels)
The Index is the list of row labels.
- By default, Pandas automatically numbers rows starting at 0 (0, 1, 2...).
- You can change the index to use words or dates instead of numbers if you want.


**Extracting:** 
If you pull a single column out of a DataFrame, it automatically becomes a Series.

## Importing Pandas

In [63]:
import numpy as np
import pandas as pd

## Pandas Series
A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Series from lists

In [64]:
# strings

names = ["Alice", "Bob", "Charlie", "Diana"]
strings_series = pd.Series(names)
print(strings_series, type(strings_series))

0      Alice
1        Bob
2    Charlie
3      Diana
dtype: str <class 'pandas.Series'>

In [65]:
# integers

numbers = [10, -5, 42, 0, 7]
numbers_series = pd.Series(numbers)
print(numbers_series, type(numbers_series))

0    10
1    -5
2    42
3     0
4     7
dtype: int64 <class 'pandas.Series'>

### Custom Indexing in Series

In [66]:
# custome index

name = ["Bob", "Lucky", "Ana"]
id = [1, 4, 7]
name_series = pd.Series(name, index=id)
print(name_series, type(name_series))

1      Bob
4    Lucky
7      Ana
dtype: str <class 'pandas.Series'>

### Naming to column
In a Pandas Series, the name attribute acts as the column header.

In [67]:
# setting a name

list_of_food = ["Apple", "Rice", "Bread", "Chicken", "BBQ", "Fish"]
list_index = [1, 3, 6, 7, 2, 4]
list_name = "MyFood"

food_series = pd.Series(list_of_food, index=list_index, name=list_name)
print(food_series, type(food_series))                                           #dtype tells about column data type

1      Apple
3       Rice
6      Bread
7    Chicken
2        BBQ
4       Fish
Name: MyFood, dtype: str <class 'pandas.Series'>

### Series from Dictionary

When you pass a dictionary to a pd.Series():
- The dictionary Keys become the Index (row labels).
- The dictionary Values become the actual Data.
- Note: You still use the name= parameter separately to give the column a header.

In [68]:
students = {
    101 : "Bob",
    102 : "Alice",
    103 : "Lucy",
    104 : "Ana"
}

dictionary_series = pd.Series(students, name="students_data")
print(dictionary_series)
print(type(dictionary_series))

101      Bob
102    Alice
103     Lucy
104      Ana
Name: students_data, dtype: str
<class 'pandas.Series'>

### Series using read_csv

* **`squeeze()`** reduces 1-dimensional DataFrames (single row or single column) into a pandas **Series**.
* **`squeeze("columns")`** targets a **single column** across multiple rows, while **`squeeze("index")`** targets a **single row** across multiple columns.

In [63]:
movies = pd.read_csv("data/movies.csv", index_col="id", usecols=(["id", "title"])).squeeze("columns")
movies
# type(movies)

id
980431              Avatar Aang: The Last Airbender
1632181                         Accidental Partners
1007757                                     Swapped
278                        The Shawshank Redemption
936075                                      Michael
                             ...
1554                                    Down by Law
1265                           Bridge to Terabithia
1054867                    One Battle After Another
439584     I Can Quit Whenever I Want 3: Ad Honorem
14534                                          Rudy
Name: title, Length: 12160, dtype: str

## Series Attributes 90–95% Core

**A Series is a single column of data in Pandas.**


| Attribute    | Simple Explanation              |
| ------------ | ------------------------------- |
| `.index`     | Shows the index                 |
| `.values`    | Shows the values                |
| `.shape`     | Shows the size                  |
| `.size`      | Number of values                |
| `.dtype`     | Shows the data type             |
| `.name`      | Shows the Series name           |
| `.empty`     | Checks if Series is empty       |
| `.is_unique` | Checks if all values are unique |

In [141]:
import pandas as pd
numbers = pd.read_csv("data/random_numbers.csv").squeeze("columns")
print(numbers)
print(type(numbers))

0       90
1       81
2       80
3       44
4       46
        ..
1186    79
1187    12
1188    53
1189    46
1190    11
Name: numbers, Length: 1191, dtype: int64
<class 'pandas.Series'>

In [ ]:
# index
numbers.index

RangeIndex(start=0, stop=1191, step=1)

In [135]:
# values
numbers.values

array([90, 81, 80, ..., 53, 46, 11], shape=(1191,))

In [ ]:
# shape (rows, columns)
numbers.shape

(1191,)

In [ ]:
# size (rows * columns)
numbers.size

1191

In [138]:
# dtype
numbers.dtype

dtype('int64')

In [139]:
# name
numbers.name

'numbers'

In [143]:
# empty
numbers.empty

False

In [145]:
# is_unique
numbers.is_unique

False

## Series Functions 90–95% Core

### 1. Inspect Data

| Method        | Simple Explanation        |
| ------------- | ------------------------- |
| `.head()`     | Shows first values        |
| `.tail()`     | Shows last values         |
| `.info()`     | Shows basic information   |
| `.describe()` | Shows statistical summary |
| `.count()`    | Counts non-missing values |

In [146]:
import pandas as pd
numbers = pd.read_csv("data/random_numbers.csv").squeeze("columns")
numbers

0       90
1       81
2       80
3       44
4       46
        ..
1186    79
1187    12
1188    53
1189    46
1190    11
Name: numbers, Length: 1191, dtype: int64

In [147]:
# head()
numbers.head()

0    90
1    81
2    80
3    44
4    46
Name: numbers, dtype: int64

In [148]:
# tail()
numbers.tail()

1186    79
1187    12
1188    53
1189    46
1190    11
Name: numbers, dtype: int64

In [149]:
# info()
numbers.info()

<class 'pandas.Series'>
RangeIndex: 1191 entries, 0 to 1190
Series name: numbers
Non-Null Count  Dtype
--------------  -----
1191 non-null   int64
dtypes: int64(1)
memory usage: 9.4 KB

In [150]:
# describe()
numbers.describe()

count    1191.000000
mean       48.692695
std        28.638247
min         1.000000
25%        24.000000
50%        49.000000
75%        74.000000
max        99.000000
Name: numbers, dtype: float64

In [151]:
# count()
numbers.count()

np.int64(1191)

### 2. Select Data

| Method       | Simple Explanation              |
| ------------ | ------------------------------- |
| `.loc[]`     | Selects using labels            |
| `.iloc[]`    | Selects using positions         |
| `.at[]`      | Gets one value by label         |
| `.iat[]`     | Gets one value by position      |
| `.isin()`    | Checks if values are in a list  |
| `.between()` | Checks if values are in a range |

In [152]:
import pandas as pd
numbers = pd.read_csv("data/random_numbers.csv").squeeze("columns")
numbers

0       90
1       81
2       80
3       44
4       46
        ..
1186    79
1187    12
1188    53
1189    46
1190    11
Name: numbers, Length: 1191, dtype: int64

In [157]:
numbers.loc[0]

np.int64(90)

In [159]:
numbers.iloc[2]

np.int64(80)

In [160]:
numbers.at[0]

np.int64(90)

In [161]:
numbers.iat[0]

np.int64(90)

In [164]:
numbers[numbers.isin([90])]

0       90
32      90
67      90
142     90
359     90
455     90
621     90
681     90
767     90
787     90
827     90
1046    90
1098    90
1133    90
1156    90
Name: numbers, dtype: int64

In [170]:
numbers[numbers.between(97, 100)]

9       98
104     97
106     98
118     99
191     97
238     98
252     99
269     99
376     99
454     97
500     99
524     97
528     97
565     99
593     98
696     98
725     98
755     99
784     97
795     97
802     99
876     99
934     98
985     99
1006    99
1071    97
1088    97
1101    99
1110    98
1119    97
1151    97
1172    99
Name: numbers, dtype: int64

### 3. Statistics

| Method        | Simple Explanation            |
| ------------- | ----------------------------- |
| `.mean()`     | Calculates average            |
| `.median()`   | Finds middle value            |
| `.mode()`     | Finds most common value       |
| `.min()`      | Finds smallest value          |
| `.max()`      | Finds largest value           |
| `.sum()`      | Calculates total              |
| `.std()`      | Calculates standard deviation |
| `.var()`      | Calculates variance           |
| `.quantile()` | Gets a percentile             |

In [171]:
import pandas as pd
numbers = pd.read_csv("data/random_numbers.csv").squeeze("columns")
numbers

0       90
1       81
2       80
3       44
4       46
        ..
1186    79
1187    12
1188    53
1189    46
1190    11
Name: numbers, Length: 1191, dtype: int64

In [185]:
# mean()
nmean = numbers.mean()
print("Mean")
print(nmean)
print("*" * 30)

# median()
nmedian = numbers.median()
print("Median")
print(nmedian)
print("*" * 30)

# mode()
nmode = numbers.mode()
print("Mode")
print(nmode)
print("*" * 30)


# min()
nmin = numbers.min()
print("Min")
print(nmin)
print("*" * 30)

# max()
nmax = numbers.max()
print("Max")
print(nmax)
print("*" * 30)

# sum()
nsum = numbers.sum()
print("Sum")
print(nsum)
print("*" * 30)

# std()
nstd = numbers.std()
print("Std")
print(nstd)
print("*" * 30)

# var()
nvar = numbers.var()
print("Var")
print(nvar)
print("*" * 30)

# quantile()
nquantile = numbers.quantile()
print("Quantile")
print(nquantile)
print("*" * 30)

Mean
48.6926952141058
******************************
Median
49.0
******************************
Mode
0     4
1    81
Name: numbers, dtype: int64
******************************
Min
1
******************************
Max
99
******************************
Sum
57993
******************************
Std
28.638246836868007
******************************
Var
820.1491818893804
******************************
Quantile
49.0
******************************

### 4. Find Values

| Method         | Simple Explanation          |
| -------------- | --------------------------- |
| `.idxmax()`    | Gets index of maximum value |
| `.idxmin()`    | Gets index of minimum value |
| `.nlargest()`  | Gets largest values         |
| `.nsmallest()` | Gets smallest values        |

In [186]:
import pandas as pd
numbers = pd.read_csv("data/random_numbers.csv").squeeze("columns")
numbers

0       90
1       81
2       80
3       44
4       46
        ..
1186    79
1187    12
1188    53
1189    46
1190    11
Name: numbers, Length: 1191, dtype: int64

In [192]:
# idxmax()
print(numbers.idxmax())
print(numbers.iloc[118])
print("*" * 30)

# idxmin()
print(numbers.idxmin())
print(numbers.iloc[109])
print("*" * 30)

# nlargest()
print(numbers.nlargest())
print("*" * 30)

# nsmallest()
print(numbers.nsmallest())
print("*" * 30)

118
99
******************************
109
1
******************************
118    99
252    99
269    99
376    99
500    99
Name: numbers, dtype: int64
******************************
109    1
125    1
251    1
522    1
529    1
Name: numbers, dtype: int64
******************************

### 5. Missing Data

| Method           | Simple Explanation         |
| ---------------- | -------------------------- |
| `.isna()`        | Finds missing values       |
| `.notna()`       | Finds non-missing values   |
| `.fillna()`      | Fills missing values       |
| `.dropna()`      | Removes missing values     |
| `.ffill()`       | Fills using previous value |
| `.bfill()`       | Fills using next value     |
| `.interpolate()` | Estimates missing values   |

In [237]:
import pandas as pd
data = pd.read_csv("data/pandas_series_all_methods_10.csv")
score = data["score"]
print(score)
print(type(score))

0    85.0
1    72.0
2    85.0
3     NaN
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64
<class 'pandas.Series'>

In [229]:
# isna()
print(score.isna())
print("*" * 30)

# notna()
print(score.notna())

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: score, dtype: bool
******************************
0     True
1     True
2     True
3    False
4     True
5     True
6     True
7     True
8     True
9     True
Name: score, dtype: bool

In [228]:
# fillna()
print(score.fillna(0))

0    85.0
1    72.0
2    85.0
3     0.0
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64

In [232]:
# dropna()
print(score)
no_na = score.dropna()
print(no_na)

0    85.0
1    72.0
2    85.0
3     NaN
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64
0    85.0
1    72.0
2    85.0
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64

In [234]:
print(score)
forward_fill = score.ffill()
print(forward_fill)

0    85.0
1    72.0
2    85.0
3     NaN
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64
0    85.0
1    72.0
2    85.0
3    85.0
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64

In [235]:
print(score)
backword_fill = score.bfill()
print(backword_fill)

0    85.0
1    72.0
2    85.0
3     NaN
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64
0    85.0
1    72.0
2    85.0
3    68.0
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64

In [236]:
print(score)
inter = score.interpolate()
print(inter)

0    85.0
1    72.0
2    85.0
3     NaN
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64
0    85.0
1    72.0
2    85.0
3    76.5
4    68.0
5    95.0
6    72.0
7    84.0
8    55.0
9    68.0
Name: score, dtype: float64

### 6. Unique & Duplicates

| Method               | Simple Explanation   |
| -------------------- | -------------------- |
| `.unique()`          | Gets unique values   |
| `.nunique()`         | Counts unique values |
| `.value_counts()`    | Counts each value    |
| `.duplicated()`      | Finds duplicates     |
| `.drop_duplicates()` | Removes duplicates   |

In [240]:
import pandas as pd
data = pd.read_csv("data/pandas_series_all_methods_10.csv")
name = data["name"]
print(name)
print(type(name))

0      Ali Khan
1     Sara Ahmed
2      Ali Khan
3      Usman Ali
4    Ayesha Noor
5    Bilal Ahmed
6     Sara Ahmed
7      Hira Khan
8    Omar Farooq
9    Ayesha Noor
Name: name, dtype: str
<class 'pandas.Series'>

In [247]:
print(name.unique())
print("*" * 30)
print(name.nunique())
print("*" * 30)
print(name.value_counts())
print("*" * 30)
print(name[name.duplicated()])
print("*" * 30)
print(name.drop_duplicates())

<StringArray>
[ ' Ali Khan ',  'Sara Ahmed',   'Usman Ali', 'Ayesha Noor', 'Bilal Ahmed',
   'Hira Khan', 'Omar Farooq']
Length: 7, dtype: str
******************************
7
******************************
name
 Ali Khan      2
Sara Ahmed     2
Ayesha Noor    2
Usman Ali      1
Bilal Ahmed    1
Hira Khan      1
Omar Farooq    1
Name: count, dtype: int64
******************************
2      Ali Khan
6     Sara Ahmed
9    Ayesha Noor
Name: name, dtype: str
******************************
0      Ali Khan
1     Sara Ahmed
3      Usman Ali
4    Ayesha Noor
5    Bilal Ahmed
7      Hira Khan
8    Omar Farooq
Name: name, dtype: str

### 7. Sorting

| Method           | Simple Explanation   |
| ---------------- | -------------------- |
| `.sort_values()` | Sorts by values      |
| `.sort_index()`  | Sorts by index       |
| `.nlargest()`    | Gets largest values  |
| `.nsmallest()`   | Gets smallest values |

In [248]:
import pandas as pd
data = pd.read_csv("data/pandas_series_all_methods_10.csv")
age = data["age"]
print(age)
print(type(age))

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64
<class 'pandas.Series'>

In [253]:
print(age.sort_values())
print("*" * 30)
print(age.sort_index())
print("*" * 30)
print(age.nlargest(n=3, keep="first"))
print("*" * 30)
print(age.nsmallest(n=3, keep="first"))
print("*" * 30)

0    22.0
2    22.0
7    24.0
1    25.0
6    25.0
4    28.0
9    28.0
3    31.0
8    35.0
5     NaN
Name: age, dtype: float64
******************************
0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64
******************************
8    35.0
3    31.0
4    28.0
Name: age, dtype: float64
******************************
0    22.0
2    22.0
7    24.0
Name: age, dtype: float64
******************************

### 8. Cleaning & Transformation

| Method              | Simple Explanation                     |
| ------------------- | -------------------------------------- |
| `.astype()`         | Changes data type                      |
| `.convert_dtypes()` | Converts to suitable Pandas data types |
| `.replace()`        | Replaces values                        |
| `.map()`            | Maps values to new values              |
| `.apply()`          | Applies a function                     |
| `.where()`          | Keeps values when condition is true    |
| `.mask()`           | Replaces values when condition is true |
| `.clip()`           | Limits values to a range               |
| `.copy()`           | Creates a separate copy                |

In [6]:
import numpy as np
import pandas as pd
data = pd.read_csv("data/pandas_series_all_methods_10.csv")
data

,id,name,age,score,city,department,salary,active,date,email
0,1,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-05 09:30:00,ALI@EXAMPLE.COM
1,2,Sara Ahmed,25.0,72.0,Lahore,HR,75000.0,False,2025-01-12 10:15:00,sara@example.com
2,3,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-19 11:00:00,ALI@EXAMPLE.COM
3,4,Usman Ali,31.0,NaN,Islamabad,Finance,90000.0,True,2025-02-03 14:20:00,usman@example.com
4,5,Ayesha Noor,28.0,68.0,NaN,HR,65000.0,False,NaN,ayesha@example.com
5,6,Bilal Ahmed,NaN,95.0,Lahore,IT,NaN,True,2025-02-18 16:45:00,NaN
6,7,Sara Ahmed,25.0,72.0,Lahore,HR,75000.0,False,2025-03-01 09:00:00,sara@example.com
7,8,Hira Khan,24.0,84.0,Karachi,Finance,85000.0,True,2025-03-14 12:30:00,hira@example.com
8,9,Omar Farooq,35.0,55.0,Multan,Marketing,150000.0,False,2025-04-02 18:10:00,omar@example.com
9,10,Ayesha Noor,28.0,68.0,Islamabad,HR,65000.0,True,2025-04-20 20:00:00,ayesha@example.com

In [7]:
age = data["age"]
print(age, type(age))

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64 <class 'pandas.Series'>

In [14]:
age_in_int = age.astype("Int16")
print(age_in_int, type(age_in_int))

0      22
1      25
2      22
3      31
4      28
5    <NA>
6      25
7      24
8      35
9      28
Name: age, dtype: Int16 <class 'pandas.Series'>

In [15]:
auto_datatype_age = age.convert_dtypes()
print(auto_datatype_age, type(auto_datatype_age))

0      22
1      25
2      22
3      31
4      28
5    <NA>
6      25
7      24
8      35
9      28
Name: age, dtype: Int64 <class 'pandas.Series'>

In [16]:
age

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64

In [ ]:
age.replace(22.0, 99)               # replace all values with your desired value

0    99.0
1    25.0
2    99.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64

In [18]:
age

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64

In [20]:
age.map(lambda x: x * 2 if x > 25 else x * 1)

0    22.0
1    25.0
2    22.0
3    62.0
4    56.0
5     NaN
6    25.0
7    24.0
8    70.0
9    56.0
Name: age, dtype: float64

In [21]:
def even(x):
    return x % 2 == 0

In [24]:
even_age =age[age.apply(even)]
even_age

0    22.0
2    22.0
4    28.0
7    24.0
9    28.0
Name: age, dtype: float64

In [25]:
age

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64

In [ ]:
age.where(age > 28, 0)          # Keep the data where this condition is true; change everything else.

0     0.0
1     0.0
2     0.0
3    31.0
4     0.0
5     0.0
6     0.0
7     0.0
8    35.0
9     0.0
Name: age, dtype: float64

In [ ]:
age.mask(age > 28, 0 )      # Hide (mask) the data where this condition is true; keep everything else.

0    22.0
1    25.0
2    22.0
3     0.0
4    28.0
5     NaN
6    25.0
7    24.0
8     0.0
9    28.0
Name: age, dtype: float64

In [43]:
age

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64

In [ ]:
# series_or_df.clip(lower=None, upper=None, inplace=False)
clipped_age = age.clip(lower=23, upper=29)                  # .clip() forces your data to stay inside a minimum and maximum limit.
clipped_age

0    23.0
1    25.0
2    23.0
3    29.0
4    28.0
5     NaN
6    25.0
7    24.0
8    29.0
9    28.0
Name: age, dtype: float64

In [44]:
copy_of_age = age.copy()

print(copy_of_age, type(copy_of_age))

0    22.0
1    25.0
2    22.0
3    31.0
4    28.0
5     NaN
6    25.0
7    24.0
8    35.0
9    28.0
Name: age, dtype: float64 <class 'pandas.Series'>

### 9. Data / Feature Operations

| Method          | Simple Explanation                   |
| --------------- | ------------------------------------ |
| `.shift()`      | Moves values up or down              |
| `.diff()`       | Calculates difference between values |
| `.pct_change()` | Calculates percentage change         |
| `.rank()`       | Gives values a rank                  |
| `.cumsum()`     | Calculates cumulative sum            |
| `.cummax()`     | Calculates cumulative maximum        |
| `.cummin()`     | Calculates cumulative minimum        |
| `.rolling()`    | Calculates rolling/window statistics |

In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv("data/pandas_series_all_methods_10.csv")
data

,id,name,age,score,city,department,salary,active,date,email
0,1,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-05 09:30:00,ALI@EXAMPLE.COM
1,2,Sara Ahmed,25.0,72.0,Lahore,HR,75000.0,False,2025-01-12 10:15:00,sara@example.com
2,3,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-19 11:00:00,ALI@EXAMPLE.COM
3,4,Usman Ali,31.0,NaN,Islamabad,Finance,90000.0,True,2025-02-03 14:20:00,usman@example.com
4,5,Ayesha Noor,28.0,68.0,NaN,HR,65000.0,False,NaN,ayesha@example.com
5,6,Bilal Ahmed,NaN,95.0,Lahore,IT,NaN,True,2025-02-18 16:45:00,NaN
6,7,Sara Ahmed,25.0,72.0,Lahore,HR,75000.0,False,2025-03-01 09:00:00,sara@example.com
7,8,Hira Khan,24.0,84.0,Karachi,Finance,85000.0,True,2025-03-14 12:30:00,hira@example.com
8,9,Omar Farooq,35.0,55.0,Multan,Marketing,150000.0,False,2025-04-02 18:10:00,omar@example.com
9,10,Ayesha Noor,28.0,68.0,Islamabad,HR,65000.0,True,2025-04-20 20:00:00,ayesha@example.com

In [8]:
date = data["date"]
date

0    2025-01-05 09:30:00
1    2025-01-12 10:15:00
2    2025-01-19 11:00:00
3    2025-02-03 14:20:00
4                    NaN
5    2025-02-18 16:45:00
6    2025-03-01 09:00:00
7    2025-03-14 12:30:00
8    2025-04-02 18:10:00
9    2025-04-20 20:00:00
Name: date, dtype: str

In [10]:
date.shift(1)

0                    NaN
1    2025-01-05 09:30:00
2    2025-01-12 10:15:00
3    2025-01-19 11:00:00
4    2025-02-03 14:20:00
5                    NaN
6    2025-02-18 16:45:00
7    2025-03-01 09:00:00
8    2025-03-14 12:30:00
9    2025-04-02 18:10:00
Name: date, dtype: str

In [11]:
score = data["score"]
score.diff()

0     NaN
1   -13.0
2    13.0
3     NaN
4     NaN
5    27.0
6   -23.0
7    12.0
8   -29.0
9    13.0
Name: score, dtype: float64

In [12]:
score.pct_change()

0         NaN
1   -0.152941
2    0.180556
3         NaN
4         NaN
5    0.397059
6   -0.242105
7    0.166667
8   -0.345238
9    0.236364
Name: score, dtype: float64

In [13]:
score.rank()

0    7.5
1    4.5
2    7.5
3    NaN
4    2.5
5    9.0
6    4.5
7    6.0
8    1.0
9    2.5
Name: score, dtype: float64

In [14]:
score.cumsum()

0     85.0
1    157.0
2    242.0
3      NaN
4    310.0
5    405.0
6    477.0
7    561.0
8    616.0
9    684.0
Name: score, dtype: float64

In [15]:
score.cummax()

0    85.0
1    85.0
2    85.0
3     NaN
4    85.0
5    95.0
6    95.0
7    95.0
8    95.0
9    95.0
Name: score, dtype: float64

In [16]:
score.cummin()

0    85.0
1    72.0
2    72.0
3     NaN
4    68.0
5    68.0
6    68.0
7    68.0
8    55.0
9    55.0
Name: score, dtype: float64

In [21]:
score.rolling(9).mean()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: score, dtype: float64

### 10. Aggregation

| Method         | Simple Explanation            |
| -------------- | ----------------------------- |
| `.agg()`       | Applies one or more functions |
| `.aggregate()` | Same as `.agg()`              |

Example:

```python
s.agg(["mean", "max", "min"])
```

In [3]:
import pandas as pd

s = pd.read_csv("data/pandas_series_all_methods_10.csv")

text_cols = ["name", "city", "department", "email"]
s[text_cols] = s[text_cols].apply(lambda x: x.str.strip())
s["email"] = s["email"].str.lower()

summary_agg = s.groupby("department").agg(
    total_salary = ("salary", "sum"),
    average_score = ("score", "mean"),
    active_count=("active", "sum"),
    unique_employees=("name", "nunique"),
).reset_index()

summary_agg.head()

  department  total_salary  average_score  active_count  unique_employees
0    Finance      175000.0      84.000000             2                 2
1         HR      280000.0      70.000000             1                 2
2         IT      120000.0      88.333333             3                 2
3  Marketing      150000.0      55.000000             0                 1

### 11. Text Data

Use `.str` for string operations.

| Method            | Simple Explanation                |
| ----------------- | --------------------------------- |
| `.str.lower()`    | Converts text to lowercase        |
| `.str.upper()`    | Converts text to uppercase        |
| `.str.strip()`    | Removes extra spaces              |
| `.str.contains()` | Checks if text contains something |
| `.str.replace()`  | Replaces text                     |
| `.str.split()`    | Splits text                       |
| `.str.len()`      | Gets text length                  |

Example:

```python
df["name"].str.lower()
```

In [ ]:
import pandas as pd
s = pd.read_csv("data/pandas_series_all_methods_10.csv")
s.head()

,id,name,age,score,city,department,salary,active,date,email
0,1,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-05 09:30:00,ALI@EXAMPLE.COM
1,2,Sara Ahmed,25.0,72.0,Lahore,HR,75000.0,False,2025-01-12 10:15:00,sara@example.com
2,3,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-19 11:00:00,ALI@EXAMPLE.COM
3,4,Usman Ali,31.0,NaN,Islamabad,Finance,90000.0,True,2025-02-03 14:20:00,usman@example.com
4,5,Ayesha Noor,28.0,68.0,NaN,HR,65000.0,False,NaN,ayesha@example.com

In [12]:
nlowers = s["name"].str.lower()
ulowers = s["name"].str.upper()
slowers = s["name"].str.strip(" ")
clowers = s["name"].str.contains("Ali")
rlowers = s["name"].str.replace("Ali", "Zei")
stlowers = s["name"].str.split("")
llowers = s["name"].str.len()

print(nlowers)
print("*" * 30)
print(ulowers)
print("*" * 30)
print(slowers)
print("*" * 30)
print(clowers)
print("*" * 30)
print(rlowers)
print("*" * 30)
print(stlowers)
print("*" * 30)
print(llowers)

0      ali khan
1     sara ahmed
2      ali khan
3      usman ali
4    ayesha noor
5    bilal ahmed
6     sara ahmed
7      hira khan
8    omar farooq
9    ayesha noor
Name: name, dtype: str
******************************
0      ALI KHAN
1     SARA AHMED
2      ALI KHAN
3      USMAN ALI
4    AYESHA NOOR
5    BILAL AHMED
6     SARA AHMED
7      HIRA KHAN
8    OMAR FAROOQ
9    AYESHA NOOR
Name: name, dtype: str
******************************
0       Ali Khan
1     Sara Ahmed
2       Ali Khan
3      Usman Ali
4    Ayesha Noor
5    Bilal Ahmed
6     Sara Ahmed
7      Hira Khan
8    Omar Farooq
9    Ayesha Noor
Name: name, dtype: str
******************************
0     True
1    False
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: bool
******************************
0      Zei Khan
1     Sara Ahmed
2      Zei Khan
3      Usman Zei
4    Ayesha Noor
5    Bilal Ahmed
6     Sara Ahmed
7      Hira Khan
8    Omar Farooq
9    Ayesha Noor
Name: name, dtype: str
******************************
0       [,  , A, l, i,  , K, h, a, n,  , ]
1       [, S, a, r, a,  , A, h, m, e, d, ]
2       [,  , A, l, i,  , K, h, a, n,  , ]
3          [, U, s, m, a, n,  , A, l, i, ]
4    [, A, y, e, s, h, a,  , N, o, o, r, ]
5    [, B, i, l, a, l,  , A, h, m, e, d, ]
6       [, S, a, r, a,  , A, h, m, e, d, ]
7          [, H, i, r, a,  , K, h, a, n, ]
8    [, O, m, a, r,  , F, a, r, o, o, q, ]
9    [, A, y, e, s, h, a,  , N, o, o, r, ]
Name: name, dtype: object
******************************
0    10
1    10
2    10
3     9
4    11
5    11
6    10
7     9
8    11
9    11
Name: name, dtype: int64

### 12. Date / Time Data

Use `.dt` for datetime operations.

| Method / Attribute | Simple Explanation          |
| ------------------ | --------------------------- |
| `pd.to_datetime()` | Converts values to datetime |
| `.dt.year`         | Gets year                   |
| `.dt.month`        | Gets month                  |
| `.dt.day`          | Gets day                    |
| `.dt.dayofweek`    | Gets day of week            |
| `.dt.date`         | Gets date                   |
| `.dt.hour`         | Gets hour                   |

Example:

```python
df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
```

In [18]:
import pandas as pd

s = pd.read_csv("data/pandas_series_all_methods_10.csv")
s["date"].info()

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: date
Non-Null Count  Dtype
--------------  -----
9 non-null      str
dtypes: str(1)
memory usage: 212.0 bytes

In [19]:
s["date"] = pd.to_datetime(s["date"])
s["date"].info()

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: date
Non-Null Count  Dtype
--------------  -----
9 non-null      datetime64[us]
dtypes: datetime64[us](1)
memory usage: 212.0 bytes

In [21]:
date = s["date"].dt.date
year = s["date"].dt.year
month = s["date"].dt.month
day = s["date"].dt.day
dayofweek = s["date"].dt.dayofweek
hour = s["date"].dt.hour

print(date)
print("*" * 30)
print(year)
print("*" * 30)
print(month)
print("*" * 30)
print(day)
print("*" * 30)
print(dayofweek)
print("*" * 30)
print(hour)

0    2025-01-05
1    2025-01-12
2    2025-01-19
3    2025-02-03
4           NaT
5    2025-02-18
6    2025-03-01
7    2025-03-14
8    2025-04-02
9    2025-04-20
Name: date, dtype: object
******************************
0    2025.0
1    2025.0
2    2025.0
3    2025.0
4       NaN
5    2025.0
6    2025.0
7    2025.0
8    2025.0
9    2025.0
Name: date, dtype: float64
******************************
0    1.0
1    1.0
2    1.0
3    2.0
4    NaN
5    2.0
6    3.0
7    3.0
8    4.0
9    4.0
Name: date, dtype: float64
******************************
0     5.0
1    12.0
2    19.0
3     3.0
4     NaN
5    18.0
6     1.0
7    14.0
8     2.0
9    20.0
Name: date, dtype: float64
******************************
0    6.0
1    6.0
2    6.0
3    0.0
4    NaN
5    1.0
6    5.0
7    4.0
8    2.0
9    6.0
Name: date, dtype: float64
******************************
0     9.0
1    10.0
2    11.0
3    14.0
4     NaN
5    16.0
6     9.0
7    12.0
8    18.0
9    20.0
Name: date, dtype: float64

### 13. Convert / Export

| Method        | Simple Explanation             |
| ------------- | ------------------------------ |
| `.to_numpy()` | Converts Series to NumPy array |
| `.to_list()`  | Converts Series to Python list |
| `.to_dict()`  | Converts Series to dictionary  |
| `.to_frame()` | Converts Series to DataFrame   |

In [25]:
import numpy as np
import pandas as pd


s = pd.read_csv("data/pandas_series_all_methods_10.csv")

In [27]:
salary = s["salary"].dropna()
salary

0     60000.0
1     75000.0
2     60000.0
3     90000.0
4     65000.0
6     75000.0
7     85000.0
8    150000.0
9     65000.0
Name: salary, dtype: float64

In [31]:
n_salary = salary.to_numpy()
np.save("salary.npy", n_salary)
n_salary

array([ 60000.,  75000.,  60000.,  90000.,  65000.,  75000.,  85000.,
       150000.,  65000.])

In [30]:
np.load("salary.npy")

array([ 60000.,  75000.,  60000.,  90000.,  65000.,  75000.,  85000.,
       150000.,  65000.])

### 14. Sampling

| Method      | Simple Explanation      |
| ----------- | ----------------------- |
| `.sample()` | Randomly selects values |

Example:

```python
s.sample(10)
```

In [33]:
import numpy as np
import pandas as pd


s = pd.read_csv("data/pandas_series_all_methods_10.csv")
s.sample(6)

,id,name,age,score,city,department,salary,active,date,email
3,4,Usman Ali,31.0,NaN,Islamabad,Finance,90000.0,True,2025-02-03 14:20:00,usman@example.com
7,8,Hira Khan,24.0,84.0,Karachi,Finance,85000.0,True,2025-03-14 12:30:00,hira@example.com
4,5,Ayesha Noor,28.0,68.0,NaN,HR,65000.0,False,NaN,ayesha@example.com
0,1,Ali Khan,22.0,85.0,Karachi,IT,60000.0,True,2025-01-05 09:30:00,ALI@EXAMPLE.COM
8,9,Omar Farooq,35.0,55.0,Multan,Marketing,150000.0,False,2025-04-02 18:10:00,omar@example.com
9,10,Ayesha Noor,28.0,68.0,Islamabad,HR,65000.0,True,2025-04-20 20:00:00,ayesha@example.com

### Simple Mental Model

```text
Series
│
├── Inspect
│   ├── head()
│   ├── tail()
│   ├── info()
│   └── describe()
│
├── Select
│   ├── loc[]
│   ├── iloc[]
│   └── isin()
│
├── Analyze
│   ├── mean()
│   ├── median()
│   ├── min()
│   ├── max()
│   └── value_counts()
│
├── Clean
│   ├── isna()
│   ├── fillna()
│   ├── dropna()
│   ├── astype()
│   └── replace()
│
├── Transform
│   ├── map()
│   ├── apply()
│   ├── shift()
│   ├── diff()
│   └── rolling()
│
├── Text
│   └── .str
│
└── Dates
    └── .dt
```

### Series Indexing

In [35]:
# integer indexing
x = pd.Series([12, 13, 45, 62, 53, 6, 72, 5])

x[1]

np.int64(13)

In [ ]:
# negative indexing 
# it doesn't work
# when index is string it will work
x[-1]

In [38]:
# slicing
x[1:3]

1    13
2    45
dtype: int64

In [42]:
x[-5:]

3    62
4    53
5     6
6    72
7     5
dtype: int64

In [43]:
x[::2]

0    12
2    45
4    53
6    72
dtype: int64

In [45]:
# fancy indexing
x[[0, 4, 5]]

0    12
4    53
5     6
dtype: int64

### Editing Series

## Pandas DataFrame — 90–95% Core

A **DataFrame** is a 2-dimensional table made of rows and columns.

### Creating DataFrame

In [1]:
import numpy as np
import pandas as pd

In [2]:
# using lists
student_data =[
    [100, 80, 10],
    [90, 84, 7],
    [120, 84, 11],
    [125, 90, 12],
]

pd.DataFrame(student_data, columns=["iq", "marks", "package"])

    iq  marks  package
0  100     80       10
1   90     84        7
2  120     84       11
3  125     90       12

In [3]:
# using dicts
student_dict = {
    "iq":[100, 90, 120, 90],
    "marks":[80, 70, 90, 67],
    "package":[7, 6, 12, 8],
}

pd.DataFrame(student_dict)

    iq  marks  package
0  100     80        7
1   90     70        6
2  120     90       12
3   90     67        8

In [7]:
# using read_csv
employees_data = pd.read_csv("data/pandas_practice_150_rows.csv")
employees_data.sample(10)

,id,name,age,score,city,department,salary,active,date,email
121,122,Taylor Reed,44.0,91.0,Manchester,HR,89500.0,True,2026-10-21 06:00:00,taylor.reed@example.com
29,30,Morgan King,27.0,74.0,Liverpool,HR,67000.0,False,2025-09-29 10:45:00,morgan.king@example.com
111,112,Taylor Smith,46.0,71.0,Manchester,HR,137000.0,False,2026-10-11 00:00:00,taylor.smith@example.com
81,82,Taylor Price,44.0,49.0,London,Marketing,145000.0,False,2026-08-19 18:15:00,taylor.price@example.com
138,139,Cameron Taylor,19.0,92.0,Glasgow,Marketing,92750.0,True,2026-11-07 09:00:00,cameron.taylor@example.com
106,107,Quinn Carter,47.0,61.0,Liverpool,HR,100750.0,True,2026-10-06 09:00:00,quinn.carter@example.com
43,44,Casey Griffin,37.0,69.0,Cardiff,HR,89000.0,False,2026-01-03 14:05:00,casey.griffin@example.com
116,117,Quinn Miller,45.0,81.0,Liverpool,HR,NaN,True,2026-10-16 15:00:00,quinn.miller@example.com
124,125,Riley Scott,29.0,75.0,Bristol,Sales,111250.0,True,2026-10-24 15:00:00,riley.scott@example.com
37,38,Jamie Gray,36.0,63.0,London,Marketing,98000.0,False,2025-11-21 19:00:00,jamie.gray@example.com

## Attributes

### 1. Attributes

| Attribute  | Simple Explanation           |
| ---------- | ---------------------------- |
| `.index`   | Shows row labels             |
| `.columns` | Shows column names           |
| `.values`  | Shows the data               |
| `.shape`   | Shows rows and columns       |
| `.size`    | Total number of values       |
| `.ndim`    | Number of dimensions         |
| `.dtypes`  | Shows data types of columns  |
| `.empty`   | Checks if DataFrame is empty |

In [ ]:
# index
employees_data.index

RangeIndex(start=0, stop=150, step=1)

In [9]:
# columns
employees_data.columns

Index(['id', 'name', 'age', 'score', 'city', 'department', 'salary', 'active',
       'date', 'email'],
      dtype='str')

In [10]:
# values
employees_data.values

array([[1, 'Alex Morgan', 22.0, ..., True, '2025-01-05 09:30:00',
        'alex@example.com'],
       [2, 'Taylor Smith', 25.0, ..., False, '2025-01-12 10:15:00',
        'taylor@example.com'],
       [3, 'Alex Morgan', 22.0, ..., True, '2025-01-19 11:00:00',
        'ALEX@EXAMPLE.COM'],
       ...,
       [150, 'Riley Scott', 26.0, ..., True, '2025-08-25 09:25:00',
        'riley.scott@example.com'],
       [149, 'Cameron Wright', 53.0, ..., True, '2026-11-17 15:00:00',
        'cameron.wright@example.com'],
       [150, 'Morgan King', 24.0, ..., True, '2026-11-18 18:00:00',
        'morgan.king@example.com']], shape=(150, 10), dtype=object)

In [11]:
# shape
employees_data.shape

(150, 10)

In [ ]:
# size              #(rows * columns)
employees_data.size

1500

In [13]:
# ndim
employees_data.ndim

2

In [14]:
# dtypes
employees_data.dtypes

id              int64
name              str
age           float64
score         float64
city              str
department        str
salary        float64
active           bool
date              str
email             str
dtype: object

In [15]:
# empty
employees_data.empty

False

## Functions

### 2. Inspect Data

| Method        | Simple Explanation          |
| ------------- | --------------------------- |
| `.head()`     | Shows first rows            |
| `.tail()`     | Shows last rows             |
| `.info()`     | Shows DataFrame information |
| `.describe()` | Shows statistical summary   |
| `.count()`    | Counts non-missing values   |

In [16]:
# head()
employees_data.head()

,id,name,age,score,city,department,salary,active,date,email
0,1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com
1,2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com
2,3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM
3,4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com
4,5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com

In [17]:
# tail()
employees_data.tail()

,id,name,age,score,city,department,salary,active,date,email
145,148,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2026-02-14 10:10:00,alex@example.com
146,149,Avery Johnson,24.0,84.0,London,Finance,85000.0,True,2025-03-14 12:30:00,avery@example.com
147,150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com
148,149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com
149,150,Morgan King,24.0,70.0,Cardiff,Sales,52500.0,True,2026-11-18 18:00:00,morgan.king@example.com

In [19]:
# info()
employees_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          150 non-null    int64
 1   name        150 non-null    str
 2   age         144 non-null    float64
 3   score       144 non-null    float64
 4   city        145 non-null    str
 5   department  150 non-null    str
 6   salary      144 non-null    float64
 7   active      150 non-null    bool
 8   date        146 non-null    str
 9   email       146 non-null    str
dtypes: bool(1), float64(3), int64(1), str(5)
memory usage: 10.8 KB

In [20]:
# describe()
employees_data.describe()

               id         age       score         salary
count  150.000000  144.000000  144.000000     144.000000
mean    75.540000   32.416667   74.600694   93041.666667
std     43.512496    9.681285   14.737515   33037.896761
min      1.000000   18.000000   45.000000   45000.000000
25%     38.250000   24.750000   63.000000   66500.000000
50%     75.500000   30.000000   76.000000   85875.000000
75%    112.750000   40.000000   87.000000  115937.500000
max    150.000000   53.000000   99.000000  180000.000000

In [21]:
# count()
employees_data.count()

id            150
name          150
age           144
score         144
city          145
department    150
salary        144
active        150
date          146
email         146
dtype: int64

In [24]:
# isnull()
employees_data.isnull().sum()

id            0
name          0
age           6
score         6
city          5
department    0
salary        6
active        0
date          4
email         4
dtype: int64

In [29]:
# dublicated #check dublicated rows
employees_data.duplicated().sum()

np.int64(0)

In [30]:
# rename()
employees_data

,id,name,age,score,city,department,salary,active,date,email
0,1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com
1,2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com
2,3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM
3,4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com
4,5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com
...,...,...,...,...,...,...,...,...,...,...
145,148,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2026-02-14 10:10:00,alex@example.com
146,149,Avery Johnson,24.0,84.0,London,Finance,85000.0,True,2025-03-14 12:30:00,avery@example.com
147,150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com
148,149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com
149,150,Morgan King,24.0,70.0,Cardiff,Sales,52500.0,True,2026-11-18 18:00:00,morgan.king@example.com

In [ ]:
employees_data.rename(columns={"city":"e_city"}) 
# employees_data.rename(columns={"city":"e_city"}, inplace=True) # permanet change

,id,name,age,score,e_city,department,salary,active,date,email
0,1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com
1,2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com
2,3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM
3,4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com
4,5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com
...,...,...,...,...,...,...,...,...,...,...
145,148,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2026-02-14 10:10:00,alex@example.com
146,149,Avery Johnson,24.0,84.0,London,Finance,85000.0,True,2025-03-14 12:30:00,avery@example.com
147,150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com
148,149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com
149,150,Morgan King,24.0,70.0,Cardiff,Sales,52500.0,True,2026-11-18 18:00:00,morgan.king@example.com

### 3. Select Data

| Method           | Simple Explanation           |
| ---------------- | ---------------------------- |
| `df["column"]`   | Selects one column           |
| `df[["A", "B"]]` | Selects multiple columns     |
| `.loc[]`         | Selects by labels/conditions |
| `.iloc[]`        | Selects by positions         |
| `.at[]`          | Gets one value by label      |
| `.iat[]`         | Gets one value by position   |

### Example

```python
df["age"]

df[["age", "salary"]]

df.loc[df["age"] > 25]

df.iloc[0:5]
```

In [40]:
# df["column"]
employees_data["city"]

0          London
1      Manchester
2          London
3      Birmingham
4             NaN
          ...
145        London
146        London
147         Leeds
148       Glasgow
149       Cardiff
Name: city, Length: 150, dtype: str

In [41]:
# df[["A", "B"]]

employees_data[["city", "name"]]

           city            name
0        London     Alex Morgan
1    Manchester    Taylor Smith
2        London     Alex Morgan
3    Birmingham    Jordan Brown
4           NaN    Casey Wilson
..          ...             ...
145      London     Alex Morgan
146      London   Avery Johnson
147       Leeds     Riley Scott
148     Glasgow  Cameron Wright
149     Cardiff     Morgan King

[150 rows x 2 columns]

In [52]:
employees = pd.read_csv("data/pandas_practice_150_rows.csv", index_col="id")
employees.head(2)

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com
2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com

In [58]:
# loc - it gives one row from dataframe with will be series
employees.loc[1]

#if you want result which will be row in datafarme then use [[]]
# employees.loc[[1]]

name                  Alex Morgan
age                          22.0
score                        85.0
city                       London
department                     IT
salary                    60000.0
active                       True
date          2025-01-05 09:30:00
email            alex@example.com
Name: 1, dtype: object

In [81]:
employees.loc[employees["age"] > 25]

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com
5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com
9,Quinn Miller,35.0,55.0,Liverpool,Marketing,150000.0,False,2025-04-02 18:10:00,quinn@example.com
10,Jamie Moore,28.0,68.0,Bristol,HR,65000.0,True,2025-04-20 20:00:00,jamie@example.com
12,Morgan Anderson,42.0,77.5,Leeds,Finance,110000.0,True,2025-05-11 13:45:00,morgan@example.com
...,...,...,...,...,...,...,...,...,...
141,Alex Parker,33.0,63.0,NaN,IT,107250.0,True,2026-11-09 15:00:00,alex.parker@example.com
142,Taylor Reed,40.0,76.0,Manchester,HR,114500.0,True,2026-11-10 18:00:00,taylor.reed@example.com
143,Jordan Kelly,47.0,89.0,Birmingham,Finance,121750.0,True,2026-11-11 21:00:00,NaN
150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com
149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com

In [ ]:
# iloc - finding with index
employees.iloc[0]
# same for datafarme [[]]
# employees.iloc[[0]]

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com

In [67]:
#  rows and columns both
employees.iloc[[0,1,2], [0,2,1]]

            name  score   age
id
1    Alex Morgan   85.0  22.0
2   Taylor Smith   72.0  25.0
3    Alex Morgan   85.0  22.0

In [71]:
# Format: df.at[row_label, column_name]
# at[]
employees.at[1, "name"]

'Alex Morgan'

In [79]:
# Format: df.iat[row_position, column_position]
# This gets the value from the 1st row (index 0) and the 3rd column (index 2)
employees.iat[0, 0]

'Alex Morgan'

### 4. Filter Rows

| Method           | Simple Explanation                  |
| ---------------- | ----------------------------------- |
| Boolean indexing | Filters rows using conditions       |
| `.isin()`        | Checks values against a list        |
| `.query()`       | Filters using a query expression    |
| `.between()`     | Checks if values are within a range |

### Example

```python
df[df["age"] > 30]

df[df["city"].isin(["Lahore", "Karachi"])]

df.query("age > 30")

df[df["age"].between(20, 30)]
```

In [82]:
employees

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com
2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com
3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM
4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com
5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com
...,...,...,...,...,...,...,...,...,...
148,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2026-02-14 10:10:00,alex@example.com
149,Avery Johnson,24.0,84.0,London,Finance,85000.0,True,2025-03-14 12:30:00,avery@example.com
150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com
149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com
150,Morgan King,24.0,70.0,Cardiff,Sales,52500.0,True,2026-11-18 18:00:00,morgan.king@example.com

In [86]:
# boolean indexing
london_employees = employees[employees["city"] == "London"]
it_employees = london_employees[london_employees["department"] == "IT"]
age_employees = it_employees[it_employees["age"] > 25]
age_employees

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
91,Alex Morgan,43.0,73.0,London,IT,104750.0,True,2026-09-20 09:00:00,alex.morgan@example.com
101,Alex Parker,41.0,93.0,London,IT,57250.0,True,NaN,alex.parker@example.com
111,Alex Morgan,39.0,58.0,London,IT,129750.0,True,2026-10-10 21:00:00,alex.morgan@example.com
131,Alex Morgan,35.0,98.0,London,IT,154750.0,True,2026-10-30 09:00:00,alex.morgan@example.com

In [93]:
e = employees
e[(e["score"] > 90) & (e["age"] < 20)]

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
11,Cameron Taylor,19.0,91.0,Oxford,IT,48000.0,True,2025-05-03 08:20:00,cameron@example.com
19,Cameron Taylor,19.0,91.0,Oxford,IT,48000.0,True,2025-07-09 14:30:00,cameron@example.com
37,Quinn Collins,18.0,99.0,Oxford,IT,45000.0,True,2025-11-15 08:10:00,quinn.collins@example.com
59,Cameron Taylor,19.0,91.0,Oxford,IT,48000.0,True,2026-04-03 10:25:00,cameron@example.com
77,Quinn Collins,18.0,99.0,Oxford,IT,45000.0,True,2026-07-20 07:45:00,quinn.collins@example.com
139,Cameron Taylor,19.0,92.0,Glasgow,Marketing,92750.0,True,2026-11-07 09:00:00,cameron.taylor@example.com

In [94]:
employees

,name,age,score,city,department,salary,active,date,email
id,,,,,,,,,
1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com
2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com
3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM
4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com
5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com
...,...,...,...,...,...,...,...,...,...
148,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2026-02-14 10:10:00,alex@example.com
149,Avery Johnson,24.0,84.0,London,Finance,85000.0,True,2025-03-14 12:30:00,avery@example.com
150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com
149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com
150,Morgan King,24.0,70.0,Cardiff,Sales,52500.0,True,2026-11-18 18:00:00,morgan.king@example.com

In [97]:
# adding new column
employees["country"] = "USA"
employees.head()

,name,age,score,city,department,salary,active,date,email,country
id,,,,,,,,,,
1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com,USA
2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com,USA
3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM,USA
4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com,USA
5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com,USA

In [ ]:
# from existing ones
employees["first_name"] = employees["name"].str.split(" ").apply(lambda x:x[0])
employees

,name,age,score,city,department,salary,active,date,email,country,first_name
id,,,,,,,,,,,
1,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-05 09:30:00,alex@example.com,USA,Alex
2,Taylor Smith,25.0,72.0,Manchester,HR,75000.0,False,2025-01-12 10:15:00,taylor@example.com,USA,Taylor
3,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2025-01-19 11:00:00,ALEX@EXAMPLE.COM,USA,Alex
4,Jordan Brown,31.0,NaN,Birmingham,Finance,90000.0,True,2025-02-03 14:20:00,jordan@example.com,USA,Jordan
5,Casey Wilson,28.0,68.0,NaN,HR,65000.0,False,NaN,casey@example.com,USA,Casey
...,...,...,...,...,...,...,...,...,...,...,...
148,Alex Morgan,22.0,85.0,London,IT,60000.0,True,2026-02-14 10:10:00,alex@example.com,USA,Alex
149,Avery Johnson,24.0,84.0,London,Finance,85000.0,True,2025-03-14 12:30:00,avery@example.com,USA,Avery
150,Riley Scott,26.0,89.0,Leeds,IT,69000.0,True,2025-08-25 09:25:00,riley.scott@example.com,USA,Riley
149,Cameron Wright,53.0,57.0,Glasgow,Marketing,NaN,True,2026-11-17 15:00:00,cameron.wright@example.com,USA,Cameron
150,Morgan King,24.0,70.0,Cardiff,Sales,52500.0,True,2026-11-18 18:00:00,morgan.king@example.com,USA,Morgan

### 5. Statistics

| Method        | Simple Explanation            |
| ------------- | ----------------------------- |
| `.mean()`     | Calculates average            |
| `.median()`   | Finds middle value            |
| `.mode()`     | Finds most common value       |
| `.min()`      | Finds smallest value          |
| `.max()`      | Finds largest value           |
| `.sum()`      | Calculates total              |
| `.std()`      | Calculates standard deviation |
| `.var()`      | Calculates variance           |
| `.quantile()` | Gets a percentile             |

### 6. Find Values

| Method         | Simple Explanation             |
| -------------- | ------------------------------ |
| `.idxmax()`    | Finds index of maximum value   |
| `.idxmin()`    | Finds index of minimum value   |
| `.nlargest()`  | Gets rows with largest values  |
| `.nsmallest()` | Gets rows with smallest values |

### Example

```python
df.nlargest(5, "salary")

df.nsmallest(5, "age")
```

### 7. Missing Data

| Method           | Simple Explanation           |
| ---------------- | ---------------------------- |
| `.isna()`        | Finds missing values         |
| `.notna()`       | Finds non-missing values     |
| `.fillna()`      | Fills missing values         |
| `.dropna()`      | Removes missing rows/columns |
| `.ffill()`       | Fills using previous value   |
| `.bfill()`       | Fills using next value       |
| `.interpolate()` | Estimates missing values     |

### 8. Unique & Duplicates

| Method               | Simple Explanation        |
| -------------------- | ------------------------- |
| `.nunique()`         | Counts unique values      |
| `.value_counts()`    | Counts unique rows/values |
| `.duplicated()`      | Finds duplicate rows      |
| `.drop_duplicates()` | Removes duplicate rows    |

### Example

```python
df["city"].nunique()

df["city"].value_counts()

df.duplicated()

df.drop_duplicates()
```

### 9. Sorting

| Method           | Simple Explanation     |
| ---------------- | ---------------------- |
| `.sort_values()` | Sorts by column values |
| `.sort_index()`  | Sorts by index         |
| `.nlargest()`    | Gets largest rows      |
| `.nsmallest()`   | Gets smallest rows     |

### Example

```python
df.sort_values("salary")

df.sort_values("salary", ascending=False)
```

### 10. Cleaning & Transformation

| Method              | Simple Explanation                  |
| ------------------- | ----------------------------------- |
| `.astype()`         | Changes data types                  |
| `.convert_dtypes()` | Converts to suitable Pandas dtypes  |
| `.replace()`        | Replaces values                     |
| `.map()`            | Applies mapping to values           |
| `.apply()`          | Applies a function                  |
| `.where()`          | Keeps values meeting a condition    |
| `.mask()`           | Replaces values meeting a condition |
| `.clip()`           | Limits values to a range            |
| `.copy()`           | Creates a separate copy             |

### Example

```python
df["age"] = df["age"].astype(int)

df["gender"] = df["gender"].replace({
    "M": "Male",
    "F": "Female"
})
```

### 11. Add / Remove / Rename Columns

| Method        | Simple Explanation             |
| ------------- | ------------------------------ |
| `.assign()`   | Creates new columns            |
| `.insert()`   | Inserts a column at a position |
| `.drop()`     | Removes rows or columns        |
| `.pop()`      | Removes and returns a column   |
| `.rename()`   | Renames columns or index       |
| `.set_axis()` | Sets column/index labels       |

### Example

```python
df = df.assign(
    income_per_age=df["income"] / df["age"]
)

df = df.drop(columns=["unnecessary_column"])

df = df.rename(columns={
    "old_name": "new_name"
})
```

### 12. Grouping & Aggregation

| Method         | Simple Explanation                          |
| -------------- | ------------------------------------------- |
| `.groupby()`   | Groups data                                 |
| `.agg()`       | Applies one or more functions               |
| `.aggregate()` | Same as `.agg()`                            |
| `.transform()` | Applies group operation while keeping shape |

### Example

```python
df.groupby("department")["salary"].mean()

df.groupby("department")["salary"].agg(["mean", "max", "min"])
```

**Very important for EDA and feature engineering.**

### 13. Combining DataFrames

| Method       | Simple Explanation                    |
| ------------ | ------------------------------------- |
| `.merge()`   | SQL-style joins                       |
| `.join()`    | Joins DataFrames using indexes/keys   |
| `.concat()`  | Combines DataFrames                   |
| `.update()`  | Updates values from another DataFrame |
| `.compare()` | Shows differences between DataFrames  |

### Example

```python
pd.merge(df1, df2, on="employee_id")

pd.concat([df1, df2])
```

### 14. Reshaping Data

| Method           | Simple Explanation                   |
| ---------------- | ------------------------------------ |
| `.pivot()`       | Reshapes data                        |
| `.pivot_table()` | Creates pivot table with aggregation |
| `.melt()`        | Converts wide data to long data      |
| `.stack()`       | Moves columns into index             |
| `.unstack()`     | Moves index into columns             |
| `.explode()`     | Converts list-like values into rows  |
| `.transpose()`   | Swaps rows and columns               |
| `.T`             | Shortcut for transpose               |

### Example

```python
df.pivot_table(
    index="department",
    values="salary",
    aggfunc="mean"
)
```

### 15. Data / Feature Operations

| Method          | Simple Explanation            |
| --------------- | ----------------------------- |
| `.shift()`      | Moves values up/down          |
| `.diff()`       | Calculates differences        |
| `.pct_change()` | Calculates percentage change  |
| `.rank()`       | Ranks values                  |
| `.cumsum()`     | Calculates cumulative sum     |
| `.cummax()`     | Cumulative maximum            |
| `.cummin()`     | Cumulative minimum            |
| `.rolling()`    | Calculates rolling statistics |

### 16. Correlation

| Method        | Simple Explanation                        |
| ------------- | ----------------------------------------- |
| `.corr()`     | Calculates correlation                    |
| `.corrwith()` | Correlation with another DataFrame/Series |
| `.cov()`      | Calculates covariance                     |

### Example

```python
df.corr(numeric_only=True)
```

Very useful during **EDA and feature selection**.

### 17. Data Types

| Method              | Simple Explanation           |
| ------------------- | ---------------------------- |
| `.astype()`         | Changes data type            |
| `.convert_dtypes()` | Converts to suitable dtypes  |
| `.select_dtypes()`  | Selects columns by data type |

### Example

```python
df.select_dtypes(include="number")

df.select_dtypes(include="object")
```

This is especially useful when preparing data for **ML models**.

### 18. Random Sampling

| Method      | Simple Explanation    |
| ----------- | --------------------- |
| `.sample()` | Randomly selects rows |

### Example

```python
df.sample(10)

df.sample(frac=0.2)
```

### 19. Text Data

Use `.str` on a column containing strings.

| Method            | Simple Explanation         |
| ----------------- | -------------------------- |
| `.str.lower()`    | Converts text to lowercase |
| `.str.upper()`    | Converts text to uppercase |
| `.str.strip()`    | Removes extra spaces       |
| `.str.contains()` | Checks for text            |
| `.str.replace()`  | Replaces text              |
| `.str.split()`    | Splits text                |
| `.str.len()`      | Gets text length           |

### Example

```python
df["name"] = df["name"].str.strip().str.lower()
```

### 20. Date / Time Data

Use `.dt` for datetime columns.

| Method / Attribute | Simple Explanation   |
| ------------------ | -------------------- |
| `pd.to_datetime()` | Converts to datetime |
| `.dt.year`         | Gets year            |
| `.dt.month`        | Gets month           |
| `.dt.day`          | Gets day             |
| `.dt.dayofweek`    | Gets day of week     |
| `.dt.date`         | Gets date            |
| `.dt.hour`         | Gets hour            |

### Example

```python
df["date"] = pd.to_datetime(df["date"])

df["year"] = df["date"].dt.year
```

### 21. Window Operations

| Method         | Simple Explanation                  |
| -------------- | ----------------------------------- |
| `.rolling()`   | Rolling calculations                |
| `.expanding()` | Uses all previous values            |
| `.ewm()`       | Exponentially weighted calculations |

### Example:

```python
df["sales"].rolling(7).mean()
```

### 22. Index Operations

| Method           | Simple Explanation       |
| ---------------- | ------------------------ |
| `.set_index()`   | Makes column the index   |
| `.reset_index()` | Resets the index         |
| `.reindex()`     | Changes/rearranges index |
| `.rename()`      | Renames index/columns    |
| `.drop()`        | Removes index/columns    |
| `.sort_index()`  | Sorts by index           |

### 23. Convert Data

| Method          | Simple Explanation       |
| --------------- | ------------------------ |
| `.to_numpy()`   | Converts to NumPy array  |
| `.to_dict()`    | Converts to dictionary   |
| `.to_records()` | Converts to record array |
| `.to_string()`  | Converts to string       |

### 24. Export Data

| Method          | Simple Explanation     |
| --------------- | ---------------------- |
| `.to_csv()`     | Saves as CSV           |
| `.to_excel()`   | Saves as Excel         |
| `.to_json()`    | Saves/converts to JSON |
| `.to_parquet()` | Saves as Parquet       |
| `.to_sql()`     | Writes to SQL database |

### Simple Mental Model

```text
DataFrame
│
├── Inspect
│   ├── head()
│   ├── tail()
│   ├── info()
│   └── describe()
│
├── Select
│   ├── ["column"]
│   ├── loc[]
│   └── iloc[]
│
├── Filter
│   ├── conditions
│   ├── isin()
│   └── query()
│
├── Analyze
│   ├── mean()
│   ├── median()
│   ├── min()
│   ├── max()
│   └── value_counts()
│
├── Clean
│   ├── isna()
│   ├── fillna()
│   ├── dropna()
│   ├── astype()
│   └── replace()
│
├── Transform
│   ├── assign()
│   ├── map()
│   ├── apply()
│   ├── shift()
│   └── rolling()
│
├── Group
│   ├── groupby()
│   ├── agg()
│   └── transform()
│
├── Combine
│   ├── merge()
│   ├── join()
│   └── concat()
│
├── Reshape
│   ├── pivot()
│   ├── pivot_table()
│   ├── melt()
│   └── explode()
│
├── Text
│   └── .str
│
└── Dates
    └── .dt
```